### ISSUE TITLE
black_turn.png が見つからない

### ISSUE THREAD

**Issue by topstone** [ebifrier/WhaleWatcher#46]
version 3.4.1.0 を起動するだけで error log に以下の通り吐き出されます。当該画像が見つからないようです。

```
2022-08-08 22:16:41.0440 ERROR	'Data\Design\Default\black_turn.png': 画像ファイルの読み込みに失敗しました。  
 Parameter is not valid.*System.ArgumentException*System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(String filename, Boolean useIcm)
   at System.Drawing.Bitmap..ctor(String filename)
   at WhaleWatcher.ViewModel.DesignViewModel.LoadImage(String imagePath)

2022-08-08 22:16:41.0774 ERROR	'Data\Design\Default\white_turn.png': 画像ファイルの読み込みに失敗しました。  
 Parameter is not valid.*System.ArgumentException*System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(String filename, Boolean useIcm)
   at System.Drawing.Bitmap..ctor(String filename)
   at WhaleWatcher.ViewModel.DesignViewModel.LoadImage(String imagePath)
```

**Comment by ebifrier** [comment]
ご報告ありがとうございます。
そのログは無視していただいて構いません。

初期状態ではこちらで画像を用意していないためそのようなログが出力されますが
画像がなくても問題なく動作するようになっております。
念のためにログを出していますが、無視していただいて全く問題ありません。

**Comment by topstone** [comment]
回答ありがとうございます。それを聞いて安心しました。(別 issue を立てる前に確認したかったので。)
